#!/bin/sh
#
# Start the network....
#

case "$1" in
  start)
 	echo "Starting network..."
	/sbin/ifup -a
 	echo "Starting inetd..."
	inetd
	;;
  stop)
	echo -n "Stopping inetd..."
	killall inetd
	echo -n "Stopping network..."
	/sbin/ifdown -a
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

